name: MyWF

on:
  workflow_dispatch:
jobs:
  my-job: 
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2

        - name: Checkout to tag
          uses: actions/checkout@v2
          with:
            repository: hazelcast/hazelcast-csharp-client
            path: tag
            ref: v5.1.0

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.9

        - name: Detect Version
          uses: madhead/semver-utils@latest        
          id: version
          with:
            version: v5.2.0
            compare-to: 5.2.x
            satisfies: 1.x

        - name: Backport SSL Tests for client < 5.2.0
          shell: pwsh
          run: |
            Write-Output "${{ steps.version.outputs.comparison-result }}  ${{steps.version.outputs.major}}"
            Write-Output "Condtition: ${{ (steps.version.outputs.major == '5' && steps.version.outputs.minor < '2') || (steps.version.outputs.major == '4') }}"
            ls $GITHUB_WORKSPACE

            ls ${{github.workspace}}/utils
            ls ${{github.workspace}}/tag

        - name: Detect Version 2
          uses: madhead/semver-utils@latest        
          id: version2
          with:
            version: v5.1.0
            compare-to: 5.2.x
            satisfies: x

        - name: Backport SSL Tests for client < 5.2.0
          shell: pwsh
          run: |
            Write-Output "${{ steps.version2.outputs.comparison-result }}  ${{steps.version2.outputs.major}}"
            Write-Output "Condtition: ${{ (steps.version2.outputs.major == '5' && steps.version2.outputs.minor < '2') || (steps.version2.outputs.major == '4') }}"            